# Global configuration options. These can also be set on each task.
queue_ahead: 360 # Number of minutes to queue jobs into the future
tz: "America/Denver" # The application time zone will be used by default if not set

morning_traffic_collect_task:
  class: "SnapshotCollectionWorker"
  every: "5.minutes"
  at: "6:00"
  expires_after: "4.hours"

afternoon_traffic_collect_task:
  class: "SnapshotCollectionWorker"
  every: "5.minutes"
  at: "1:00"
  expires_after: "4.hours"
